# syntax=docker/dockerfile:1
FROM python:3

RUN pip install --upgrade pip



ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt --root-user-action=ignore
COPY . /code/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
